class _Themes():

    def __init__(self, graph_attrs=None, cluster_attrs=None, node_attrs=None, edge_attrs=None):

        self.graph_attrs = {
            "bgcolor": "transparent",
            "center": "false",
            "charset": "utf-8",
            "clusterrank": "local",
            "colorscheme": "",
            "comment": "",
            "compound": "false",
            "concentrate": "false",
            "fontcolor": "black",
            "fontname": "times-roman",
            "fontpath": "system-dependent",
            "fontsize": "14",
            "forcelabels": "true",
            "gradientangle": "",
            "imagepath": "",
            "label": "",
            "labeljust": "c",
            "labelloc": "b",
            "landscape": "false",
            "layout": "dot",
            "margin": "8",
            "mclimit": "1",
            "newrank": "false",
            "nodesep": "0.25",
            "nojustify": "false",
            "nslimit": "",
            "nslimit1": "",
            "ordering": "",
            "orientation": "0",
            "outputorder": "breadthfirst",
            "pack": "false",
            # "packmode": "node",
            "pad": "0.0555",
            "pagedir": "bl",
            "quantum": "0.0",
            "rankdir": "tb",
            "ranksep": "0.5",
            "ratio": "auto",
            "remincross": "true",
            "rotate": "0",
            "searchsize": "30",
            "showboxes": "0",
            "size": "",
            "sortv": "0",
            "splines": "line",
            "style": "",
            "viewport": "",
        }

        self.cluster_attrs = {
            "bgcolor": "transparent",
            "color": "black",
            "colorscheme": "",
            "fillcolor": "black",
            "fontcolor": "black",
            "fontname": "times-roman",
            "fontsize": "14",
            "gradientangle": "",
            "label": "",
            "labeljust": "c",
            "labelloc": "t",
            "layer": "",
            "margin": "8",
            "nojustify": "false",
            "pencolor": "black",
            "penwidth": "1",
            "peripheries": "1",
            "sortv": "0",
            "style": "",
        }

        self.node_attrs = {
            "color": "black",
            "colorscheme": "",
            "comment": "",
            "distortion": "0",
            "fillcolor": "lightgrey",
            "fixedsize": "false",
            "fontcolor": "black",
            "fontname": "times-roman",
            "fontsize": "14",
            "gradientangle": "",
            "group": "",
            "height": "0.5",
            "image": "",
            "imagepos": "mc",
            "imagescale": "false",
            "label": "",
            "labelloc": "c",
            "layer": "",
            "margin": "0.11,0.055",
            "nojustify": "false",
            "ordering": "",
            "orientation": "0",
            "penwidth": "1",
            "peripheries": "1",
            "pos": "",
            "regular": "false",
            "shape": "ellipse",
            "shapefile": "",
            "showboxes": "0",
            "sides": "4",
            "skew": "0",
            "sortv": "0",
            "style": "",
            "width": "0.75",
            "xlabel": "",
        }

        self.edge_attrs = {
            "arrowhead": "normal",
            "arrowsize": "1",
            "arrowtail": "normal",
            "color": "black",
            "colorscheme": "",
            "comment": "",
            "constraint": "true",
            "decorate": "false",
            "dir": "forward",
            "fillcolor": "lightgrey",
            "fontcolor": "black",
            "fontname": "times-roman",
            "fontsize": "14",
            "headclip": "true",
            "headlabel": "",
            "headport": "center",
            "label": "",
            "labelangle": "-25",
            "labeldistance": "1",
            "labelfloat": "false",
            "labelfontcolor": "black",
            "labelfontname": "times-roman",
            "labelfontsize": "14",
            "layer": "",
            "lhead": "",
            "ltail": "",
            "minlen": "1",
            "nojustify": "false",
            "penwidth": "1",
            "pos": "",
            "samehead": "",
            "sametail": "",
            "showboxes": "0",
            "style": "",
            "tailclip": "true",
            "taillabel": "",
            "tailport": "center",
            "weight": "1",
            "xlabel": "",
        }

        def update_graph_attrs(graph_attrs):
            self.graph_attrs.update(graph_attrs)
        
        def update_cluster_attrs(cluster_attrs):
            self.cluster_attrs.update(cluster_attrs)

        def update_node_attrs(node_attrs):
            self.node_attrs.update(node_attrs)

        def update_edge_attrs(edge_attrs):
            self.edge_attrs.update(edge_attrs)

class Default(_Themes):
    
    pass