name: Publish to Codecov

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        brew update && brew upgrade
        brew doctor

        brew uninstall ruby

        brew install rbenv
        brew install ruby-build
        echo 'export RBENV_ROOT=/usr/local/var/rbenv' >> ~/.bash_profile
        echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile

        rbenv install 2.2.2
        rbenv global 2.2.2

        brew install graphviz

        python -m pip install --upgrade pip
        pip install pytest-cov
        pip install coverage
        pip install graphviz
    - run: python -m pytest --cov=architectures tests --cov-report xml
    - run: bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
    env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}