name: Run Test Suites

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pip install pytest-cov
    - run: python -m pytest --cov=architectures tests --cov-report xml
    - run: bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
    env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}