name: Publish to Codecov

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt-get remove ruby

        brew install rbenv

        sudo apt update
        sudo apt install git curl libssl-dev libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev

        curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash -

        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(rbenv init -)"' >> ~/.bashrc
        source ~/.bashrc

        brew install graphviz

        python -m pip install --upgrade pip
        pip install pytest-cov
        pip install coverage
        pip install graphviz
    - run: python -m pytest --cov=architectures tests --cov-report xml
    - run: bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
    env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}