name: Publish to Codecov

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt-get remove ruby

        sudo apt --fix-broken install python-pycurl python-apt

        cd $HOME
        sudo apt-get update 
        sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev

        git clone https://github.com/rbenv/rbenv.git ~/.rbenv
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(rbenv init -)"' >> ~/.bashrc
        exec $SHELL

        git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
        echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
        exec $SHELL

        rbenv install 2.3.1
        rbenv global 2.3.1
        ruby -v
        gem install nokogiri -- --with-xslt-dir=/home/linuxbrew/.linuxbrew/opt/libxslt
        brew install graphviz
        python -m pip install --upgrade pip
        pip install pytest-cov
        pip install coverage
        pip install graphviz
    - run: python -m pytest --cov=architectures tests --cov-report xml
    - run: bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
    env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}